version: "3"

services:
  app:
    build: .
    environment:
      - LISTEN_ADDR=:8080
      - LOG_FILE=log.txt
    volumes:
      - ./logs:/root/logs
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/window9u.me:/etc/nginx:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
