name: deploy_homeServer

on:
  push:
    branches: ["depl"]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/toy-project

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      - name: Execute deployment script on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOCKER_IMAGE
          script: |
            docker pull $DOCKER_IMAGE
            docker stop toy-project || true
            docker rm toy-project || true
            docker run -d --name toy-project \
            -p 80:80 \
            -v ${{ secrets.LOG_PATH }}:/app/log.txt \
            --restart unless-stopped \
            $DOCKER_IMAGE
